/**
 * User Repository Interface
 * 
 * This interface defines the contract for user data access operations.
 * It follows the Repository Pattern, providing an abstraction layer between
 * the domain logic and data persistence layer.
 * 
 * @module domain/interfaces/IUserRepository
 * 
 * @remarks
 * This interface is part of the Domain Layer in Clean Architecture.
 * Implementations should be in the Infrastructure Layer.
 * 
 * @example
 * ```typescript
 * class UserRepository implements IUserRepository {
 *   async findByUsername(username: string): Promise<User | null> {
 *     // Implementation using database
 *   }
 * }
 * ```
 */

import { User, UserWithoutPassword } from '../entities/User';

/**
 * Repository interface for user data operations
 * 
 * Provides methods to interact with user data storage without exposing
 * implementation details of the underlying data source (database, API, etc.)
 */
export interface IUserRepository {
  /**
   * Finds a user by their username
   * 
   * @param {string} username - The username to search for
   * @returns {Promise<User | null>} The user object with password hash, or null if not found
   * @throws {Error} If database query fails
   * 
   * @example
   * ```typescript
   * const user = await userRepository.findByUsername('john_doe');
   * if (user) {
   *   // User found, can verify password
   * }
   * ```
   */
  findByUsername(username: string): Promise<User | null>;

  /**
   * Finds a user by their ID
   * 
   * Returns user data without the password hash for security reasons.
   * Use this method when you need user information but not authentication data.
   * 
   * @param {number} id - The user ID to search for
   * @returns {Promise<UserWithoutPassword | null>} User object without password, or null if not found
   * @throws {Error} If database query fails
   * 
   * @example
   * ```typescript
   * const user = await userRepository.findById(123);
   * if (user) {
   *   console.log(user.username, user.role);
   * }
   * ```
   */
  findById(id: number): Promise<UserWithoutPassword | null>;

  /**
   * Creates a new user in the database
   * 
   * Inserts a new user record and returns the created user without the password hash.
   * The ID, createdAt, and updatedAt fields are automatically generated by the database.
   * 
   * @param {Omit<User, 'id' | 'createdAt' | 'updatedAt'>} userData - User data to create
   * @property {string} userData.username - Unique username
   * @property {string} userData.passwordHash - Hashed password (use bcrypt)
   * @property {'Admin' | 'Accountant' | 'Employee' | 'Management'} userData.role - User role
   * @property {number | null} [userData.employeeId] - Optional linked employee ID
   * @returns {Promise<UserWithoutPassword>} The created user without password hash
   * @throws {Error} If username already exists or database insertion fails
   * 
   * @example
   * ```typescript
   * const newUser = await userRepository.create({
   *   username: 'john_doe',
   *   passwordHash: hashedPassword,
   *   role: 'Employee',
   *   employeeId: 5
   * });
   * ```
   */
  create(userData: Omit<User, 'id' | 'createdAt' | 'updatedAt'>): Promise<UserWithoutPassword>;

  /**
   * Updates user profile information
   * 
   * Updates user data (username, role, employeeId) and returns the updated user without password hash.
   * The updatedAt timestamp is automatically updated by the database.
   * 
   * @param {number} id - The user ID to update
   * @param {Partial<Omit<User, 'id' | 'passwordHash' | 'createdAt' | 'updatedAt'>>} userData - User data to update
   * @property {string} [userData.username] - New username (must be unique)
   * @property {'Admin' | 'Accountant' | 'Employee' | 'Management'} [userData.role] - New role
   * @property {number | null} [userData.employeeId] - New employee ID
   * @returns {Promise<UserWithoutPassword>} The updated user without password hash
   * @throws {Error} If user not found, username already exists, or update fails
   * 
   * @example
   * ```typescript
   * const updatedUser = await userRepository.update(123, {
   *   username: 'new_username',
   *   role: 'Admin'
   * });
   * ```
   */
  update(id: number, userData: Partial<Omit<User, 'id' | 'passwordHash' | 'createdAt' | 'updatedAt'>>): Promise<UserWithoutPassword>;

  /**
   * Updates user password
   * 
   * Updates the password hash for a user. The new password should be hashed
   * using bcrypt before calling this method.
   * 
   * @param {number} id - The user ID to update
   * @param {string} newPasswordHash - The new hashed password
   * @returns {Promise<boolean>} True if password was updated successfully, false if user not found
   * @throws {Error} If database update fails
   * 
   * @example
   * ```typescript
   * const hashedPassword = await bcrypt.hash('newPassword123', 10);
   * const success = await userRepository.updatePassword(123, hashedPassword);
   * ```
   */
  updatePassword(id: number, newPasswordHash: string): Promise<boolean>;

  /**
   * Finds a user by their linked employee ID
   * 
   * @param {number} employeeId - The employee ID to search for
   * @returns {Promise<UserWithoutPassword | null>} User object without password, or null if not found
   * @throws {Error} If database query fails
   */
  findByEmployeeId(employeeId: number): Promise<UserWithoutPassword | null>;
}

